@startuml
start
:Найти узел для удаления;
if (Узел найден?) then (да)
  if (Узел имеет 2 потомка?) then (да)
    :Найти преемника (минимальный узел в правом поддереве);
    :Скопировать значение преемника в удаляемый узел;
    :Перенести указатель на преемника;
  endif

 if (Узел имеет одного потомка?) then (да)
    :Переместить потомка на место удаляемого узла;
  else
    :Узел - листовой, просто удалить;
  endif

 if (Удаленный узел был черным?) then (да)
    :Запустить fixDeletion для балансировки;
  endif
else (нет)
  :Завершить (узел не найден);
endif
stop
@enduml
