@startuml
start
:Найти место для нового узла;
if (Дерево пусто?) then (да)
  :Создать черный корень;
  stop
else (нет)
  :Создать красный узел;
  :Добавить его к родителю;
endif

while (Родитель узла красный?) is (да)
  :Определить дедушку;
  if (Родитель левый ребенок?) then (да)
    :Определить дядю (правый ребенок дедушки);
    if (Дядя красный?) then (да)
      :Перекрасить родителя и дядю в черный;
      :Перекрасить дедушку в красный;
      :Переместить указатель на дедушку;
    else (нет)
      if (Узел является правым ребенком?) then (да)
        :Левый поворот вокруг родителя;
        :Переместить узел на уровень выше;
      endif
      :Перекрасить родителя в черный;
      :Перекрасить дедушку в красный;
      :Правый поворот вокруг дедушки;
    endif
  else (нет)
    :Определить дядю (левый ребенок дедушки);
    if (Дядя красный?) then (да)
      :Перекрасить родителя и дядю в черный;
      :Перекрасить дедушку в красный;
      :Переместить указатель на дедушку;
    else (нет)
      if (Узел является левым ребенком?) then (да)
        :Правый поворот вокруг родителя;
        :Переместить узел на уровень выше;
      endif
      :Перекрасить родителя в черный;
      :Перекрасить дедушку в красный;
      :Левый поворот вокруг дедушки;
    endif
  endif
endwhile

:Убедиться, что корень черный;
stop
@enduml
